name: SonarCloud Analysis

on:
  push:
    branches:
      - master  # or your branch name
  pull_request:
    branches:
      - master  # or your branch name

jobs:
  sonarcloud:
    name: Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: nikhilzach
          projectKey: nikhilzach_maindemo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
