name: SonarCloud Analysis

on:
  push:
    branches:
      - master  # or any other branch you want to monitor
  pull_request:
    branches:
      - master  # or any other branch you want to monitor

jobs:
  sonarcloud:
    name: Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          entryPoint: "sonar-scanner"
          args: "-Dsonar.projectKey=nikhilzach_maindemo -Dsonar.organization=nikhilzach -Dsonar.login=${{ secrets.SONAR_TOKEN }}"
